# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'group_add.ui'
#
# Created: Sun Sep 11 16:59:42 2016
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnPlus = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlus.setGeometry(QtCore.QRect(820, 40, 93, 28))
        self.btnPlus.setObjectName("btnPlus")
        self.addGroup = QtWidgets.QPushButton(self.centralwidget)
        self.addGroup.setGeometry(QtCore.QRect(820, 160, 93, 28))
        self.addGroup.setObjectName("addGroup")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 181, 23))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.groupEdit = QtWidgets.QLineEdit(self.widget)
        self.groupEdit.setObjectName("groupEdit")
        self.horizontalLayout.addWidget(self.groupEdit)
        self.groupMember_3 = QtWidgets.QWidget(self.centralwidget)
        self.groupMember_3.setGeometry(QtCore.QRect(10, 40, 803, 25))
        self.groupMember_3.setObjectName("groupMember_3")
        self.groupMember = QtWidgets.QHBoxLayout(self.groupMember_3)
        self.groupMember.setContentsMargins(0, 0, 0, 0)
        self.groupMember.setObjectName("groupMember")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.name = QtWidgets.QLabel(self.groupMember_3)
        self.name.setObjectName("name")
        self.horizontalLayout_2.addWidget(self.name)
        self.nameEdit = QtWidgets.QLineEdit(self.groupMember_3)
        self.nameEdit.setObjectName("nameEdit")
        self.horizontalLayout_2.addWidget(self.nameEdit)
        self.groupMember.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.type = QtWidgets.QLabel(self.groupMember_3)
        self.type.setObjectName("type")
        self.horizontalLayout_6.addWidget(self.type)
        self.typeInput = QtWidgets.QComboBox(self.groupMember_3)
        self.typeInput.setObjectName("typeInput")
        self.typeInput.addItem("")
        self.typeInput.addItem("")
        self.typeInput.addItem("")
        self.typeInput.addItem("")
        self.typeInput.addItem("")
        self.typeInput.addItem("")
        self.horizontalLayout_6.addWidget(self.typeInput)
        self.groupMember.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.width = QtWidgets.QLabel(self.groupMember_3)
        self.width.setObjectName("width")
        self.horizontalLayout_8.addWidget(self.width)
        self.widthEdit = QtWidgets.QLineEdit(self.groupMember_3)
        self.widthEdit.setObjectName("widthEdit")
        self.horizontalLayout_8.addWidget(self.widthEdit)
        self.groupMember.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.value = QtWidgets.QLabel(self.groupMember_3)
        self.value.setObjectName("value")
        self.horizontalLayout_9.addWidget(self.value)
        self.valueEdit = QtWidgets.QLineEdit(self.groupMember_3)
        self.valueEdit.setObjectName("valueEdit")
        self.horizontalLayout_9.addWidget(self.valueEdit)
        self.groupMember.addLayout(self.horizontalLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnPlus.clicked['bool'].connect(self.groupMember_3.show)
        self.btnPlus.clicked['bool'].connect(self.groupMember_3.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnPlus.setText(_translate("MainWindow", "Plus"))
        self.addGroup.setText(_translate("MainWindow", "Add Group"))
        self.label.setText(_translate("MainWindow", "Group Name"))
        self.name.setText(_translate("MainWindow", "Name"))
        self.type.setText(_translate("MainWindow", "Type"))
        self.typeInput.setItemText(0, _translate("MainWindow", "input"))
        self.typeInput.setItemText(1, _translate("MainWindow", "output reg"))
        self.typeInput.setItemText(2, _translate("MainWindow", "output wire"))
        self.typeInput.setItemText(3, _translate("MainWindow", "inout"))
        self.typeInput.setItemText(4, _translate("MainWindow", "parameter"))
        self.typeInput.setItemText(5, _translate("MainWindow", "localparam"))
        self.width.setText(_translate("MainWindow", "Width"))
        self.value.setText(_translate("MainWindow", "Value"))

if __name__ == '__main__':

    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
